# Generated by Django 3.0.4 on 2020-03-15 17:54

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20200315_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awards.Profile'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_url',
            field=models.URLField(null=True),
        ),
    ]
